// +build generate
/*
WolfenGo - https://github.com/gdm85/wolfengo
Copyright (C) 2016~2019 gdm85

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	glVer := os.Args[1]

	parts := strings.Split(glVer, ".")
	major, minor := parts[0][1:], parts[1]

	// remove '-core'
	minor = strings.Replace(minor, "-core", "", 1)

	fmt.Printf(`// Code generated by src/gl/generate/generate.go DO NOT EDIT
package gl

import "github.com/go-gl/gl/%s/gl"

const (
	RequestedContextVersionMajor = %s
	RequestedContextVersionMinor = %s
)

const (
	VERTEX_SHADER        = gl.VERTEX_SHADER
	FRAGMENT_SHADER      = gl.FRAGMENT_SHADER
	DEBUG_SEVERITY_HIGH  = gl.DEBUG_SEVERITY_HIGH
	VERSION              = gl.VERSION
	DEBUG_OUTPUT         = gl.DEBUG_OUTPUT
	CW                   = gl.CW
	BACK                 = gl.BACK
	CULL_FACE            = gl.CULL_FACE
	DEPTH_TEST           = gl.DEPTH_TEST
	BLEND                = gl.BLEND
	SRC_ALPHA            = gl.SRC_ALPHA
	ONE_MINUS_SRC_ALPHA  = gl.ONE_MINUS_SRC_ALPHA
	DEPTH_CLAMP          = gl.DEPTH_CLAMP
	TEXTURE_2D           = gl.TEXTURE_2D
	COLOR_BUFFER_BIT     = gl.COLOR_BUFFER_BIT
	DEPTH_BUFFER_BIT     = gl.DEPTH_BUFFER_BIT
	ARRAY_BUFFER         = gl.ARRAY_BUFFER
	ELEMENT_ARRAY_BUFFER = gl.ELEMENT_ARRAY_BUFFER
	STATIC_DRAW          = gl.STATIC_DRAW
	FLOAT                = gl.FLOAT
	TRIANGLES            = gl.TRIANGLES
	UNSIGNED_INT         = gl.UNSIGNED_INT
	INFO_LOG_LENGTH      = gl.INFO_LOG_LENGTH
	LINK_STATUS          = gl.LINK_STATUS
	FALSE                = gl.FALSE
	VALIDATE_STATUS      = gl.VALIDATE_STATUS
	COMPILE_STATUS       = gl.COMPILE_STATUS
	TEXTURE_MIN_FILTER   = gl.TEXTURE_MIN_FILTER
	TEXTURE_WRAP_T       = gl.TEXTURE_WRAP_T
	REPEAT               = gl.REPEAT
	TEXTURE_WRAP_S       = gl.TEXTURE_WRAP_S
	NEAREST              = gl.NEAREST
	TEXTURE_MAG_FILTER   = gl.TEXTURE_MAG_FILTER
	RGBA8                = gl.RGBA8
	RGBA                 = gl.RGBA
	UNSIGNED_BYTE        = gl.UNSIGNED_BYTE
)

var (
	DrawElements             = gl.DrawElements
	Init                     = gl.Init
	GoStr                    = gl.GoStr
	GetString                = gl.GetString
	DebugMessageCallback     = gl.DebugMessageCallback
	Enable                   = gl.Enable
	ClearColor               = gl.ClearColor
	FrontFace                = gl.FrontFace
	CullFace                 = gl.CullFace
	BlendFunc                = gl.BlendFunc
	Clear                    = gl.Clear
	GenBuffers               = gl.GenBuffers
	BindBuffer               = gl.BindBuffer
	BufferData               = gl.BufferData
	Ptr                      = gl.Ptr
	EnableVertexAttribArray  = gl.EnableVertexAttribArray
	VertexAttribPointer      = gl.VertexAttribPointer
	PtrOffset                = gl.PtrOffset
	DisableVertexAttribArray = gl.DisableVertexAttribArray
	CreateProgram            = gl.CreateProgram
	UseProgram               = gl.UseProgram
	Strs                     = gl.Strs
	GetUniformLocation       = gl.GetUniformLocation
	GetProgramiv             = gl.GetProgramiv
	GetProgramInfoLog        = gl.GetProgramInfoLog
	GetShaderiv              = gl.GetShaderiv
	GetShaderInfoLog         = gl.GetShaderInfoLog
	Str                      = gl.Str
	LinkProgram              = gl.LinkProgram
	ValidateProgram          = gl.ValidateProgram
	CreateShader             = gl.CreateShader
	ShaderSource             = gl.ShaderSource
	CompileShader            = gl.CompileShader
	AttachShader             = gl.AttachShader
	Uniform3f                = gl.Uniform3f
	UniformMatrix4fv         = gl.UniformMatrix4fv
	BindTexture              = gl.BindTexture
	GenTextures              = gl.GenTextures
	TexParameteri            = gl.TexParameteri
	TexParameterf            = gl.TexParameterf
	TexImage2D               = gl.TexImage2D
	GenVertexArrays          = gl.GenVertexArrays
	BindVertexArray          = gl.BindVertexArray
)
`, glVer, major, minor)
}
